build:
    image: default-bionic
    nodes:
        analysis:
            dependencies:
                override:
                    - composer install -n --prefer-dist
            tests:
                override:
                    - command: XDEBUG_MODE=coverage php ./bin/phpunit --coverage-text --coverage-clover=coverage.clover
                      coverage:
                          file: ./coverage.clover
                          format: clover
                    - php-scrutinizer-run

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: ["src/*"]

tools:
    php_code_coverage: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_cpd: true
